/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/2ueqsatE71o
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Taviraj } from 'next/font/google'

taviraj({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function Conferance() {
  return (
    <main className="flex flex-col">
      <section className="w-full py-20 md:py-32 bg-gray-100 dark:bg-gray-800">
        <div className="container px-4 md:px-6">
          <div className="flex flex-col items-center text-center space-y-4">
            <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl">Homborsund AI Conference</h1>
            <p className="text-3xl text-rose-800 tracking-tighter sm:text-4xl md:text-5xl">August 17th 2024</p>
            <p className="max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400">Back to Basics</p>
            <p className="max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400">
              Join us for a deep dive into the fundamentals of AI, where we&apos;ll explore the core concepts and techniques
              that power the latest advancements.
            </p>
            <p className="max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400">
              No tech allowed, just you and your curiosity.
            </p>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32">
        <div className="container px-4 md:px-6">
          <div className="flex flex-col items-center text-center space-y-4">
            <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">Schedule</div>
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Conference Schedule</h2>
            <p className="max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400">
              Explore the lineup of thought-provoking talks and interactive sessions.
            </p>
          </div>
          <div className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-1 lg:gap-12">
            <div className="space-y-4">
              <div className="grid gap-1">
                <h3 className="text-xl font-bold">Day 1</h3>
                <p className="text-gray-500 dark:text-gray-400">16:00 - 18:00: Drinks and food, networking</p>
                <p className="text-gray-500 dark:text-gray-400">18:00 - 19:30: Various introductions</p>
                <p className="text-gray-500 dark:text-gray-400">19:30 - 21:00: AI: Are we there yet?</p>
                <p className="text-gray-500 dark:text-gray-400">21:00 - 22:00: And what next?</p>
                <p className="text-gray-500 dark:text-gray-400">22:00 - Late: Let&apos;s talk about it</p>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
        <div className="container px-4 md:px-6">
          <div className="flex flex-col items-center text-center space-y-4">
            <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">Speakers</div>
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Meet the Speakers</h2>
            <p className="max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400">
              Learn from industry experts and thought leaders in the field of AI.
            </p>
          </div>
          <div className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-3 lg:gap-12">
            <div className="flex flex-col items-center space-y-4">
              <img
                alt="Speaker"
                className="rounded-full"
                height="150"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "150/150",
                  objectFit: "cover",
                }}
                width="150"
              />
              <div className="space-y-1 text-center">
                <h3 className="text-xl font-bold">Eivind</h3>
                <p className="text-gray-500 dark:text-gray-400">Random TOGAF nerd</p>
              </div>
            </div>
            <div className="flex flex-col items-center space-y-4">
              <img
                alt="Speaker"
                className="rounded-full"
                height="150"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "150/150",
                  objectFit: "cover",
                }}
                width="150"
              />
              <div className="space-y-1 text-center">
                <h3 className="text-xl font-bold">Øyvind</h3>
                <p className="text-gray-500 dark:text-gray-400">Random dev nerd</p>
              </div>
            </div>
            <div className="flex flex-col items-center space-y-4">
              <img
                alt="Speaker"
                className="rounded-full"
                height="150"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "150/150",
                  objectFit: "cover",
                }}
                width="150"
              />
              <div className="space-y-1 text-center">
                <h3 className="text-xl font-bold">Rebekka (please come!)</h3>
                <p className="text-gray-500 dark:text-gray-400">Random AI nerd</p>
              </div>
            </div>
          </div>
          <div className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-3 lg:gap-12">
            <div className="flex flex-col items-center space-y-4">
              <img
                alt="Speaker"
                className="rounded-full"
                height="150"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "150/150",
                  objectFit: "cover",
                }}
                width="150"
              />
              <div className="space-y-1 text-center">
                <h3 className="text-xl font-bold">Lars</h3>
                <p className="text-gray-500 dark:text-gray-400">Random ERP nerd</p>
              </div>
            </div>
            <div className="flex flex-col items-center space-y-4">
              <img
                alt="Speaker"
                className="rounded-full"
                height="150"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "150/150",
                  objectFit: "cover",
                }}
                width="150"
              />
              <div className="space-y-1 text-center">
                <h3 className="text-xl font-bold">And you!</h3>
                <p className="text-gray-500 dark:text-gray-400">...</p>
              </div>
            </div>
            <div className="flex flex-col items-center space-y-4">
              <img
                alt="Speaker"
                className="rounded-full"
                height="150"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "150/150",
                  objectFit: "cover",
                }}
                width="150"
              />
              <div className="space-y-1 text-center">
                <h3 className="text-xl font-bold">Ofc, you!</h3>
                <p className="text-gray-500 dark:text-gray-400">....</p>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32">
        <div className="container px-4 md:px-6">
          <div className="flex flex-col items-center text-center space-y-4">
            <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">Venue</div>
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Homborsund Community Center</h2>
            <p className="max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400">
              The conference will be held at the Vågsholt skole, a historic building located in the heart
              of Krømpe.
            </p>
          </div>
          <div className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-2 lg:gap-12">
            <img
              alt="Venue"
              className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full"
              height="310"
              src="/placeholder.svg"
              width="550"
            />
            <div className="space-y-4">
              <div className="grid gap-1">
                <h3 className="text-xl font-bold">Address</h3>
                <p className="text-gray-500 dark:text-gray-400">Krømpe 16, Grimstad, Eide, Norway</p>
              </div>
              <div className="grid gap-1">
                <h3 className="text-xl font-bold">Parking</h3>
                <p className="text-gray-500 dark:text-gray-400">Free parking is available on-site.</p>
              </div>
              <div className="grid gap-1">
                <h3 className="text-xl font-bold">Accessibility</h3>
                <p className="text-gray-500 dark:text-gray-400">The venue is wheelchair accessible.</p>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32 border-t">
        <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
          <div className="space-y-3">
            <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">
              Join us at the Homborsund AI Conference
            </h2>
            <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              Register now to secure your spot and be a part of this exciting event.
            </p>
          </div>
          <div className="mx-auto w-full max-w-sm space-y-2">
            <Link
              className="inline-flex h-10 items-center justify-center rounded-md bg-gray-900 px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
              href="#"
            >
              Register Now
            </Link>
            <p className="text-xs text-gray-500 dark:text-gray-400">Early bird tickets available until May 1st.</p>
          </div>
        </div>
      </section>
    </main>
  )
}
