"use client";

/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/2ueqsatE71o
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Taviraj } from 'next/font/google'

taviraj({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import Image from "next/image"
import { useEffect } from "react"
import { Button } from "@/components/ui/button";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar";
import { HelpCircle, Lightbulb, Users } from "lucide-react"; // Added lucide-react icons

type SummitData = {
  title: string;
  date: string;
  theme: string;
  description: string[];
  schedule: { time: string; event: string }[];
  status: 'Upcoming' | 'Completed';
}

type SummitsData = {
  [key: string]: SummitData;
}

const summits: SummitsData = {
  "2024": {
    title: "Homborsund AI Conference",
    date: "August 17th 2024",
    theme: "Back to Basics",
    description: [
      "Join us for a deep dive into the fundamentals of AI, where we'll explore the core concepts and techniques that power the latest advancements.",
      "No tech allowed, just you and your curiosity."
    ],
    schedule: [
      { time: "16:00 - 18:00", event: "Drinks and food, networking" },
      { time: "18:00 - 19:30", event: "Various introductions" },
      { time: "19:30 - 21:00", event: "AI: Are we there yet?" },
      { time: "21:00 - 22:00", event: "And what next?" },
      { time: "22:00 - Late", event: "Let's talk about it" }
    ],
    status: "Completed"
  },
  "2025.1": {
    title: "Homborsund AI Summit",
    date: "3. Mai 2025",
    theme: "Agentic & Multimodal AI: Beyond GenAI with o4-mini & The Hardware Wars",
    description: [
      "The second annual gathering for AI enthusiasts and professionals to discuss real-world applications and the future of artificial intelligence, focusing on agentic capabilities and multimodal interaction.",
      "Experience the latest breakthroughs just weeks after the expected release of OpenAI's o4-mini and o3 models, alongside competitors like GPT-4.5 Orion, Claude 3.7 Sonnet, and Grok 3 — exploring the shift towards AI agents that can reason, use tools (like Codex CLI!), understand diverse data types, and perhaps one day, take physical form.",
      "But it's not all about GenAI! This year we're diving deep into the silicon battles, the rise of agentic frameworks, multimodal understanding, the path towards general-purpose agents, and the ML approaches that power our AI.",
      "No tech allowed, just you and your curiosity — we'll provide the inspiration in nature's own environment, far from the hum of NVIDIA's H200 server farms."
    ],
    schedule: [
      { time: "16:00 - 18:00", event: "Welcome reception and networking (please bring food and drinks to share - bring something that even a trained chef ML model would approve of!)" },
      { time: "18:00 - 19:00", event: "Opening keynote: 'The Great GPU Hunger Games' - How NVIDIA went from gaming company to AI overlord, and why Jensen Huang's leather jacket contains more computing power than the entire Internet circa 2005" },
      { time: "19:00 - 20:00", event: "Panel: 'DeepSeek vs NVIDIA: David's Slingshot Moment' - How DeepSeek's R1 model is challenging NVIDIA's dominance by bypassing traditional GPU constraints" },
      { time: "20:00 - 21:00", event: "Workshop: 'Traditional ML's Revenge: When Simple Models Beat Giant Transformers' - Interactive demonstrations of when good old decision trees and random forests outperform their ChatGPT cousins" },
      { time: "21:00 - 22:00", event: "Debate: 'ML vs GenAI: The Battle for AI's Soul' - Has the GenAI hype overshadowed the steady progress in traditional ML? Two teams, one utedo toilet break, unlimited philosophical ammunition" },
      { time: "22:00 - Late", event: "Campfire discussions under the stars - 'Ghost Stories About Runaway Training Jobs and Other AI Horrors' - Bring blankets, warm drinks, and your most expensive failed experiment stories" }
    ],
    status: "Upcoming"
  },
  "2025.2": {
    title: "Homborsund AI Festival",
    date: "TBD",
    theme: "Flashy Agents & Friendly Robots",
    description: [
      "Our third gathering pushes AI into the physical world with robots, drones and more.",
      "Expect shiny demos and hands-on sessions powered by the latest agentic models.",
      "Full program will drop after the summer—keep your calendars open!"
    ],
    schedule: [
      { time: "16:00 - 17:00", event: "Arrival, snacks and mingling" },
      { time: "17:00 - 18:00", event: "Keynote: 'Agents Everywhere'" },
      { time: "18:00 - 19:30", event: "Demo Jam & Breakouts" },
      { time: "19:30 - Late", event: "BBQ, bonfire and lightning talks" }
    ],
    status: "Upcoming"
  }
}

const DEFAULT_YEAR = "2025.2";

type ConferanceProps = {
  year?: string;
}

export function Conferance({ year = DEFAULT_YEAR }: ConferanceProps) {
  const activeYear = Object.keys(summits).includes(year) ? year : DEFAULT_YEAR;
  const activeSummit = summits[activeYear];

  // Add smooth scrolling for anchor links
  useEffect(() => {
    const handleAnchorClick = (e: MouseEvent) => {
      const target = e.target as HTMLElement;
      if (target.tagName === 'A' && target.getAttribute('href')?.startsWith('#')) {
        e.preventDefault();
        const id = target.getAttribute('href')?.substring(1);
        const element = document.getElementById(id || '');
        if (element) {
          window.scrollTo({
            top: element.offsetTop - 80, // Offset to account for sticky header/padding
            behavior: 'smooth'
          });
        }
      }
    };

    document.addEventListener('click', handleAnchorClick);
    return () => document.removeEventListener('click', handleAnchorClick);
  }, []);

  return (
    <main className="flex flex-col min-h-screen bg-gradient-to-br from-slate-900 via-blue-950 to-teal-900 text-white">
      <section className="w-full py-12 md:py-16"> {/* Updated padding and removed old background */}
        <div className="container px-4 md:px-6">
          <div className="flex flex-row justify-center gap-3 md:gap-4 mb-10 md:mb-12"> {/* Adjusted gap and margin */}
            {Object.keys(summits).map((summitYear) => (
              <Link
                key={summitYear}
                href={`/summit/${summitYear}`}
                className={`px-5 py-3 md:px-6 rounded-lg text-sm font-medium transition-all duration-300 transform hover:scale-105 ${
                  activeYear === summitYear
                    ? "bg-cyan-600 text-white shadow-lg"
                    : "bg-slate-700 hover:bg-slate-600 text-gray-300 border border-slate-600"
                }`}
              >
                Summit {summitYear}
                {summits[summitYear].status === "Upcoming" && summitYear === DEFAULT_YEAR && (
                  <span className="ml-2 text-xs bg-green-400 text-slate-900 px-2 py-0.5 rounded-full"> {/* Adjusted badge color */}
                    Next
                  </span>
                )}
              </Link>
            ))}
          </div>

          <div className="flex flex-col items-center text-center space-y-3 md:space-y-4"> {/* Adjusted space-y */}
            <h1 className="text-5xl md:text-6xl lg:text-7xl font-bold tracking-tight mb-4 text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 to-blue-600">{activeSummit.title}</h1>
            <p className="text-3xl md:text-4xl text-cyan-400 mb-2">{activeSummit.date}</p>
            <p className="text-xl md:text-2xl text-gray-300 max-w-3xl mb-6">{activeSummit.theme}</p>
            <div className="space-y-3"> {/* Added wrapper for description paragraphs */}
              {activeSummit.description.map((paragraph, index) => (
                <p key={index} className="text-lg text-gray-400 max-w-2xl mx-auto">
                  {paragraph}
                </p>
              ))}
            </div>
            
            {/* Navigation links for 2025.1 */}
            {activeYear === "2025.1" && (
              <div className="w-full max-w-4xl mt-10 md:mt-12"> {/* Adjusted margin */}
                <h3 className="text-2xl font-semibold mb-6 text-center text-gray-200">Jump to a section:</h3>
                <div className="grid grid-cols-2 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4"> {/* Adjusted gap */}
                  <Button asChild variant="outline" size="lg" className="border-cyan-500 text-cyan-400 hover:bg-cyan-500 hover:text-slate-900 flex items-center justify-center text-base py-3">
                    <a href="#schedule">Schedule</a>
                  </Button>
                  <Button asChild variant="outline" size="lg" className="border-cyan-500 text-cyan-400 hover:bg-cyan-500 hover:text-slate-900 flex items-center justify-center text-base py-3">
                    <a href="#topics">Hot Topics</a>
                  </Button>
                  <Button asChild variant="outline" size="lg" className="border-cyan-500 text-cyan-400 hover:bg-cyan-500 hover:text-slate-900 flex items-center justify-center text-base py-3">
                    <a href="#norwegian">Norwegian ML</a>
                  </Button>
                  <Button asChild variant="outline" size="lg" className="border-cyan-500 text-cyan-400 hover:bg-cyan-500 hover:text-slate-900 flex items-center justify-center text-base py-3">
                    <a href="#attend">How to Attend</a>
                  </Button>
                  <Button asChild variant="outline" size="lg" className="border-cyan-500 text-cyan-400 hover:bg-cyan-500 hover:text-slate-900 flex items-center justify-center text-base py-3">
                    <a href="#speakers">Speakers</a>
                  </Button>
                  <Button asChild variant="outline" size="lg" className="border-cyan-500 text-cyan-400 hover:bg-cyan-500 hover:text-slate-900 flex items-center justify-center text-base py-3">
                    <a href="#venue">Venue</a>
                  </Button>
                  <Button asChild variant="outline" size="lg" className="border-cyan-500 text-cyan-400 hover:bg-cyan-500 hover:text-slate-900 flex items-center justify-center text-base py-3">
                    <a href="#experience">Experience</a>
                  </Button>
                  <Button asChild variant="outline" size="lg" className="border-rose-500 text-rose-400 hover:bg-rose-500 hover:text-slate-900 flex items-center justify-center text-base py-3 col-span-2 md:col-span-1 lg:col-span-1">
                    <a href="#register">Register Now</a>
                  </Button>
                </div>
              </div>
            )}
          </div>
        </div>
      </section>
      <section id="schedule" className="w-full scroll-mt-16 bg-slate-800 bg-opacity-50"> {/* Updated section background */}
        <div className="container mx-auto px-4 md:px-6 py-12 md:py-16"> {/* Added inner div with padding */}
          <div className="flex flex-col items-center text-center space-y-4 mb-10 md:mb-12"> {/* Added margin-bottom */}
            <div className="bg-cyan-500 text-slate-900 font-semibold px-4 py-1 rounded-full text-sm">Schedule</div> {/* Updated small "Schedule" div */}
            <h2 className="text-4xl md:text-5xl font-bold tracking-tight text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 to-blue-600 mb-3">Summit Schedule</h2> {/* Updated h2 */}
            <p className="max-w-[700px] text-gray-300 md:text-lg"> {/* Updated descriptive paragraph */}
              Explore the lineup of thought-provoking talks and interactive sessions.
            </p>
          </div>
          <div className="mx-auto max-w-3xl w-full"> {/* Wrapper for the Card */}
            <Card className="bg-slate-800 border-slate-700 shadow-lg">
              <CardHeader>
                <CardTitle className="text-3xl font-semibold text-center text-gray-100">
                  Day 1 {/* Assuming "Day 1" for now */}
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-6 px-6 py-8"> {/* Increased padding */}
                {activeSummit.schedule.map((item, index) => (
                  <div key={index} className="flex items-start space-x-4 p-4 rounded-lg bg-slate-700 bg-opacity-50 hover:bg-slate-600/70 transition-colors duration-200">
                    <Badge variant="outline" className="border-cyan-500 text-cyan-400 text-sm font-semibold px-3 py-1 whitespace-nowrap">
                      {item.time}
                    </Badge>
                    <p className="text-gray-300 text-base leading-relaxed">{item.event}</p>
                  </div>
                ))}
              </CardContent>
            </Card>
            </div>
          </div>
        </div>
      </section>
      {/* Add Hot Topics section between Schedule and Speakers sections */}
      {activeYear === "2025.1" && (
        <section id="topics" className="w-full py-12 md:py-16 scroll-mt-16 bg-slate-800 bg-opacity-50">
          <div className="container mx-auto px-4 md:px-6">
            <div className="flex flex-col items-center text-center space-y-4 mb-10 md:mb-12">
              <div className="bg-cyan-500 text-slate-900 font-semibold px-4 py-1 rounded-full text-sm inline-block">Hot Topics</div>
              <h2 className="text-4xl md:text-5xl font-bold tracking-tight text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 to-blue-600 mb-3">2025&apos;s Cutting-Edge AI Trends</h2>
              <p className="max-w-[700px] text-gray-300 md:text-lg mx-auto">
                Our summit will explore the most revolutionary AI developments just emerging in 2025, including agentic models like OpenAI&apos;s o4-mini.
              </p>
            </div>
            
            <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
              {[
                { title: "o4-mini & o3: Next-Gen Reasoning & Multimodality", description: "Dive into OpenAI&apos;s newest models (o4-mini, o3) combining advanced reasoning with multimodal skills (image analysis, generation) and agentic tool use via interfaces like Codex CLI.", number: "01" },
                { title: "Agentic AI: Models That Act", description: "Explore how models like o4-mini are becoming agents, capable of using tools (Python, web search, image analysis) autonomously to solve complex, multi-step problems.", number: "02" },
                { title: "NVIDIA&apos;s H200 vs DeepSeek Revolution", description: "The great silicon showdown: NVIDIA&apos;s $40,000 H200 GPUs power most AI, but DeepSeek&apos;s R1 model challenges this dominance with a radically different approach that bypasses traditional APIs.", number: "03" },
                { title: "ML&apos;s Renaissance: XGBoost Strikes Back", description: "While GenAI hogs the spotlight, traditional machine learning frameworks have evolved—sometimes outperforming transformer models with 1/1000th the parameters. Come witness XGBoost&apos;s revenge tour.", number: "04" },
                { title: "MoE Architecture: When One Expert Isn&apos;t Enough", description: "DeepSeek&apos;s 671B parameter Mixture-of-Experts model demonstrates how specialized neural pathways—not just raw parameter count—drive breakthrough performance at a fraction of the training cost.", number: "05" },
                { title: "Benchmarking Agent Intelligence", description: "How do we measure the &apos;intelligence&apos; of models like o4-mini when they can use tools and interact multimodally? Explore the latest benchmarks and evaluation techniques.", number: "06" },
                { title: "General Purpose Agents & Robotics", description: "Beyond specialized tasks: discussing the roadmap towards general-purpose AI agents that can learn, adapt, and potentially operate in the physical world as robots.", number: "07" }
              ].map((topic, index) => (
                <Card key={index} className="bg-slate-800 border-slate-700 shadow-xl rounded-xl overflow-hidden hover:shadow-cyan-500/30 hover:border-cyan-500/60 transition-all duration-300 transform hover:-translate-y-1 flex flex-col">
                  <CardHeader className="pb-4">
                    <div className="flex items-center justify-between">
                      <CardTitle className="text-xl font-semibold text-gray-100">{topic.title}</CardTitle>
                      <Badge variant="outline" className="border-cyan-500 text-cyan-400 text-lg font-bold">{topic.number}</Badge>
                    </div>
                  </CardHeader>
                  <CardContent className="flex-grow">
                    <p className="text-gray-400 text-sm">{topic.description}</p>
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>
        </section>
      )}
      {/* Add new Norwegian Experience section before the Venue section */}
      {activeYear === "2025.1" && (
        <section id="norwegian" className="w-full py-12 md:py-16 scroll-mt-16 bg-transparent"> {/* Updated background */}
          <div className="container mx-auto px-4 md:px-6"> {/* Added container */}
            <div className="flex flex-col items-center text-center space-y-4 mb-10 md:mb-12">
              <div className="bg-cyan-500 text-slate-900 font-semibold px-4 py-1 rounded-full text-sm inline-block">Norwegian ML Experience</div>
              <h2 className="text-4xl md:text-5xl font-bold tracking-tight text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 to-blue-600 mb-3">Machine Learning, Norwegian Style</h2>
              <p className="max-w-[700px] text-gray-300 md:text-lg mx-auto">
                What Norway lacks in silicon, we make up for in scenic beauty and philosophical clarity.
              </p>
            </div>
            
            <div className="mx-auto max-w-3xl w-full"> {/* Wrapper for the Card */}
              <Card className="bg-slate-800 border-slate-700 shadow-xl rounded-xl overflow-hidden p-6 md:p-8"> {/* Added padding to card */}
                <CardHeader className="p-0 pb-6"> {/* Removed default padding, added bottom padding */}
                  <CardTitle className="text-3xl font-semibold text-gray-100 text-center">The Norwegian ML Philosophy</CardTitle>
                </CardHeader>
                <CardContent className="p-0 text-gray-300 text-left space-y-4"> {/* Removed default padding */}
                  <p>
                    While Silicon Valley argues about which $100 million model is best, Norwegians have been quietly applying ML in practical ways that actually help people. Learn how:
                  </p>
                  <ul className="list-disc pl-6 space-y-2 marker:text-cyan-400">
                    <li><span className="font-semibold text-gray-200">Neural nets for fishing forecasts:</span> Local ML models predict optimal fishing conditions with 85% accuracy using 1000x less compute than a single ChatGPT query</li>
                    <li><span className="font-semibold text-gray-200">Random forests for actual forests:</span> Predicting bark beetle outbreaks using lightweight ML that runs on solar power</li>
                    <li><span className="font-semibold text-gray-200">Gradient boosting vs. avalanches:</span> How a 5MB model saves lives every winter</li>
                    <li><span className="font-semibold text-gray-200">When your utedo needs AI:</span> (Trick topic - utedos definitely don&apos;t need AI, and that&apos;s the point!)</li>
                  </ul>
                  <p className="italic text-cyan-300 pt-2">
                    &quot;Sometimes the most advanced technology is knowing when to use no technology at all.&quot; — Norwegian proverb we just made up but sounds legit
                  </p>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
      )}
      {/* Add How to Attend section for 2025 summit */}
      {activeYear === "2025.1" && (
        <section id="attend" className="w-full py-12 md:py-16 scroll-mt-16 bg-slate-800 bg-opacity-50">
          <div className="container mx-auto px-4 md:px-6">
            <div className="flex flex-col items-center text-center space-y-4 mb-10 md:mb-12">
              <div className="bg-cyan-500 text-slate-900 font-semibold px-4 py-1 rounded-full text-sm inline-block">How to Attend</div>
              <h2 className="text-4xl md:text-5xl font-bold tracking-tight text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 to-blue-600 mb-3">Join the Conversation</h2>
              <p className="max-w-[700px] text-gray-300 md:text-lg mx-auto">
                The Homborsund AI Summit is an invitation... that you extend to yourself.
              </p>
            </div>
            
            <div className="grid md:grid-cols-1 lg:grid-cols-3 gap-8 mb-12">
              <Card className="bg-slate-800 border-slate-700 shadow-xl rounded-xl overflow-hidden hover:shadow-cyan-500/30 hover:border-cyan-500/60 transition-all duration-300 transform hover:-translate-y-1 flex flex-col items-center text-center p-6">
                <HelpCircle className="w-16 h-16 text-cyan-400 mb-6" />
                <CardHeader className="p-0 pb-3">
                  <CardTitle className="text-2xl font-semibold text-gray-100">Want to Attend?</CardTitle>
                </CardHeader>
                <CardContent className="p-0 flex-grow">
                  <p className="text-gray-400">
                    That&apos;s the first and most important step. If you&apos;re reading this and thinking &quot;I&apos;d like to be there&quot; - congratulations, you&apos;ve completed the most crucial part of the registration process.
                  </p>
                </CardContent>
              </Card>
              
              <Card className="bg-slate-800 border-slate-700 shadow-xl rounded-xl overflow-hidden hover:shadow-cyan-500/30 hover:border-cyan-500/60 transition-all duration-300 transform hover:-translate-y-1 flex flex-col items-center text-center p-6">
                <Lightbulb className="w-16 h-16 text-cyan-400 mb-6" />
                <CardHeader className="p-0 pb-3">
                  <CardTitle className="text-2xl font-semibold text-gray-100">Know Something</CardTitle>
                </CardHeader>
                <CardContent className="p-0 flex-grow">
                  <p className="text-gray-400">
                    Bring your knowledge—whether it&apos;s vast expertise in transformer architectures or just a persistent curiosity about why ChatGPT hallucinates your birthday. What matters is what YOU know, and what YOU want to learn.
                  </p>
                </CardContent>
              </Card>
              
              <Card className="bg-slate-800 border-slate-700 shadow-xl rounded-xl overflow-hidden hover:shadow-cyan-500/30 hover:border-cyan-500/60 transition-all duration-300 transform hover:-translate-y-1 flex flex-col items-center text-center p-6">
                <Users className="w-16 h-16 text-cyan-400 mb-6" />
                <CardHeader className="p-0 pb-3">
                  <CardTitle className="text-2xl font-semibold text-gray-100">Tell Someone</CardTitle>
                </CardHeader>
                <CardContent className="p-0 flex-grow">
                  <p className="text-gray-400">
                    Invite yourself by clicking the registration link, then tell a fellow AI enthusiast about the summit. The best learning happens in small groups of passionate people—each person you invite enriches the experience for everyone.
                  </p>
                </CardContent>
              </Card>
            </div>

            <Card className="bg-slate-800 border-slate-700 shadow-xl rounded-xl overflow-hidden p-6 md:p-8 border-l-4 border-cyan-500 mb-12">
              <CardHeader className="p-0 pb-4">
                <CardTitle className="text-2xl font-semibold text-gray-100">The Self-Invitation Philosophy</CardTitle>
              </CardHeader>
              <CardContent className="p-0 text-gray-300 space-y-3">
                <p>
                  Unlike mainstream conferences with prohibitive price tags and elaborate registration processes, we believe in simplicity. If you feel called to join our gathering of minds, we trust that you&apos;ll:
                </p>
                <ul className="list-disc pl-6 space-y-2 marker:text-cyan-400">
                  <li><strong>Bring the right spirit</strong> — A blend of curiosity, openness, and willingness to disconnect from technology to connect with ideas and people</li>
                  <li><strong>Contribute to the potluck</strong> — Both literally (bring food/drinks) and figuratively (bring ideas, questions, and enthusiasm)</li>
                  <li><strong>Extend the circle</strong> — Invite someone who would add value to our discussions (but remember space is limited to 30 participants)</li>
                </ul>
                <p className="italic text-cyan-300 pt-2">
                  &quot;The best gatherings are those where each person feels personally responsible for its success.&quot;
                </p>
              </CardContent>
            </Card>
            
            <div className="flex flex-col items-center">
              <Button size="lg" asChild className="bg-gradient-to-r from-cyan-500 to-blue-600 hover:from-cyan-600 hover:to-blue-700 text-white font-semibold py-3 px-8 rounded-lg text-lg shadow-lg hover:shadow-blue-500/50 transition-all duration-300 transform hover:scale-105">
                <Link href="https://chat.whatsapp.com/FWv18Iz2r59CuQb98LBuUQ">
                  I&apos;m Inviting Myself
                </Link>
              </Button>
              <p className="text-sm text-gray-400 mt-3">
                Join our WhatsApp community and introduce yourself
              </p>
            </div>
          </div>
        </section>
      )}
      <section id="speakers" className="w-full py-12 md:py-16 scroll-mt-16 bg-slate-900"> {/* Updated padding and background */}
        <div className="container mx-auto px-4 md:px-6"> {/* Added container with padding */}
          <div className="flex flex-col items-center text-center space-y-4 mb-10 md:mb-12"> {/* Added margin-bottom */}
            <div className="bg-cyan-500 text-slate-900 font-semibold px-4 py-1 rounded-full text-sm">Speakers</div> {/* Updated small "Speakers" div */}
            <h2 className="text-4xl md:text-5xl font-bold tracking-tight text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 to-blue-600 mb-3">Meet the Speakers</h2> {/* Updated h2 */}
            <p className="max-w-[700px] text-gray-300 md:text-lg"> {/* Updated descriptive paragraph */}
              Learn from industry experts and thought leaders in the field of AI.
            </p>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-8"> {/* Updated grid layout and gap */}
            
            {/* Eivind */}
            <Card className="bg-slate-800 border-slate-700 shadow-lg hover:shadow-cyan-500/30 transition-all duration-300 transform hover:-translate-y-1 flex flex-col items-center text-center p-6 rounded-xl">
              <Avatar className="w-32 h-32 mb-6 border-4 border-slate-700 shadow-md">
                <AvatarImage src="/placeholder.svg" alt="Eivind" />
                <AvatarFallback className="text-2xl bg-slate-600 text-gray-300">EI</AvatarFallback>
              </Avatar>
              <h3 className="text-2xl font-semibold text-gray-100 mb-1">Eivind</h3>
              <p className="text-cyan-400 text-sm">Random TOGAF nerd</p>
            </Card>

            {/* Øyvind */}
            <Card className="bg-slate-800 border-slate-700 shadow-lg hover:shadow-cyan-500/30 transition-all duration-300 transform hover:-translate-y-1 flex flex-col items-center text-center p-6 rounded-xl">
              <Avatar className="w-32 h-32 mb-6 border-4 border-slate-700 shadow-md">
                <AvatarImage src="/placeholder.svg" alt="Øyvind" />
                <AvatarFallback className="text-2xl bg-slate-600 text-gray-300">ØY</AvatarFallback>
              </Avatar>
              <h3 className="text-2xl font-semibold text-gray-100 mb-1">Øyvind</h3>
              <p className="text-cyan-400 text-sm">Random dev nerd</p>
            </Card>

            {/* Rebekka */}
            <Card className="bg-slate-800 border-slate-700 shadow-lg hover:shadow-cyan-500/30 transition-all duration-300 transform hover:-translate-y-1 flex flex-col items-center text-center p-6 rounded-xl">
              <Avatar className="w-32 h-32 mb-6 border-4 border-slate-700 shadow-md">
                <AvatarImage src="/placeholder.svg" alt="Rebekka (please come!)" />
                <AvatarFallback className="text-2xl bg-slate-600 text-gray-300">RE</AvatarFallback>
              </Avatar>
              <h3 className="text-2xl font-semibold text-gray-100 mb-1">Rebekka (please come!)</h3>
              <p className="text-cyan-400 text-sm">Random AI nerd</p>
            </Card>

            {/* Lars */}
            <Card className="bg-slate-800 border-slate-700 shadow-lg hover:shadow-cyan-500/30 transition-all duration-300 transform hover:-translate-y-1 flex flex-col items-center text-center p-6 rounded-xl">
              <Avatar className="w-32 h-32 mb-6 border-4 border-slate-700 shadow-md">
                <AvatarImage src="/placeholder.svg" alt="Lars" />
                <AvatarFallback className="text-2xl bg-slate-600 text-gray-300">LA</AvatarFallback>
              </Avatar>
              <h3 className="text-2xl font-semibold text-gray-100 mb-1">Lars</h3>
              <p className="text-cyan-400 text-sm">Random ERP nerd</p>
            </Card>

            {/* Andreas */}
            <Card className="bg-slate-800 border-slate-700 shadow-lg hover:shadow-cyan-500/30 transition-all duration-300 transform hover:-translate-y-1 flex flex-col items-center text-center p-6 rounded-xl">
              <Avatar className="w-32 h-32 mb-6 border-4 border-slate-700 shadow-md">
                <AvatarImage src="/placeholder.svg" alt="Andreas" />
                <AvatarFallback className="text-2xl bg-slate-600 text-gray-300">AN</AvatarFallback>
              </Avatar>
              <h3 className="text-2xl font-semibold text-gray-100 mb-1">Andreas</h3>
              <p className="text-cyan-400 text-sm">Random robotics nerd</p>
            </Card>

            {/* Michael */}
            <Card className="bg-slate-800 border-slate-700 shadow-lg hover:shadow-cyan-500/30 transition-all duration-300 transform hover:-translate-y-1 flex flex-col items-center text-center p-6 rounded-xl">
              <Avatar className="w-32 h-32 mb-6 border-4 border-slate-700 shadow-md">
                <AvatarImage src="/placeholder.svg" alt="Michael" />
                <AvatarFallback className="text-2xl bg-slate-600 text-gray-300">MI</AvatarFallback>
              </Avatar>
              <h3 className="text-2xl font-semibold text-gray-100 mb-1">Michael</h3>
              <p className="text-cyan-400 text-sm">Ex-Game Dev, AI/GIS wizard, public sector value creator & year-round swimmer.</p>
            </Card>

            {/* Christoffer */}
            <Card className="bg-slate-800 border-slate-700 shadow-lg hover:shadow-cyan-500/30 transition-all duration-300 transform hover:-translate-y-1 flex flex-col items-center text-center p-6 rounded-xl">
              <Avatar className="w-32 h-32 mb-6 border-4 border-slate-700 shadow-md">
                <AvatarImage src="/placeholder.svg" alt="Christoffer" />
                <AvatarFallback className="text-2xl bg-slate-600 text-gray-300">CH</AvatarFallback>
              </Avatar>
              <h3 className="text-2xl font-semibold text-gray-100 mb-1">Christoffer</h3>
              <p className="text-cyan-400 text-sm">Random puzzle-solving business nerd</p>
            </Card>

            {/* Kjetil */}
            <Card className="bg-slate-800 border-slate-700 shadow-lg hover:shadow-cyan-500/30 transition-all duration-300 transform hover:-translate-y-1 flex flex-col items-center text-center p-6 rounded-xl">
              <Avatar className="w-32 h-32 mb-6 border-4 border-slate-700 shadow-md">
                <AvatarImage src="/placeholder.svg" alt="Kjetil" />
                <AvatarFallback className="text-2xl bg-slate-600 text-gray-300">KJ</AvatarFallback>
              </Avatar>
              <h3 className="text-2xl font-semibold text-gray-100 mb-1">Kjetil</h3>
              <p className="text-cyan-400 text-sm">Random bicycle-powered system dev nerd</p>
            </Card>
            
            {/* And you! */}
            <Card className="bg-slate-800 border-slate-700 shadow-lg hover:shadow-cyan-500/30 transition-all duration-300 transform hover:-translate-y-1 flex flex-col items-center text-center p-6 rounded-xl">
              <Avatar className="w-32 h-32 mb-6 border-4 border-slate-700 shadow-md">
                <AvatarImage src="/placeholder.svg" alt="And you!" />
                <AvatarFallback className="text-2xl bg-slate-600 text-gray-300">AY</AvatarFallback>
              </Avatar>
              <h3 className="text-2xl font-semibold text-gray-100 mb-1">And you!</h3>
              <p className="text-cyan-400 text-sm">...</p>
            </Card>

            {/* Ofc, you! */}
            <Card className="bg-slate-800 border-slate-700 shadow-lg hover:shadow-cyan-500/30 transition-all duration-300 transform hover:-translate-y-1 flex flex-col items-center text-center p-6 rounded-xl">
              <Avatar className="w-32 h-32 mb-6 border-4 border-slate-700 shadow-md">
                <AvatarImage src="/placeholder.svg" alt="Ofc, you!" />
                <AvatarFallback className="text-2xl bg-slate-600 text-gray-300">OY</AvatarFallback>
              </Avatar>
              <h3 className="text-2xl font-semibold text-gray-100 mb-1">Ofc, you!</h3>
              <p className="text-cyan-400 text-sm">....</p>
            </Card>

            {/* Erik */}
            <Card className="bg-slate-800 border-slate-700 shadow-lg hover:shadow-cyan-500/30 transition-all duration-300 transform hover:-translate-y-1 flex flex-col items-center text-center p-6 rounded-xl">
              <Avatar className="w-32 h-32 mb-6 border-4 border-slate-700 shadow-md">
                <AvatarImage src="/placeholder.svg" alt="Erik" />
                <AvatarFallback className="text-2xl bg-slate-600 text-gray-300">ER</AvatarFallback>
              </Avatar>
              <h3 className="text-2xl font-semibold text-gray-100 mb-1">Erik</h3>
              <p className="text-cyan-400 text-sm">Enterprise Architecture & economic wiz</p>
            </Card>

            {/* Knut - conditional */}
            {parseFloat(activeYear) >= 2025.2 && (
            <Card className="bg-slate-800 border-slate-700 shadow-lg hover:shadow-cyan-500/30 transition-all duration-300 transform hover:-translate-y-1 flex flex-col items-center text-center p-6 rounded-xl">
              <Avatar className="w-32 h-32 mb-6 border-4 border-slate-700 shadow-md">
                <AvatarImage src="/placeholder.svg" alt="Knut" />
                <AvatarFallback className="text-2xl bg-slate-600 text-gray-300">KN</AvatarFallback>
              </Avatar>
              <h3 className="text-2xl font-semibold text-gray-100 mb-1">Knut</h3>
              <p className="text-cyan-400 text-sm">Random chatty boat maker</p>
            </Card>
            )}
          </div>
        </div>
      </section>
      <section id="venue" className="w-full py-12 md:py-24 lg:py-32 scroll-mt-16">
        <div className="container px-4 md:px-6">
          <div className="flex flex-col items-center text-center space-y-4">
            <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">Venue</div>
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
              {activeYear === DEFAULT_YEAR ? (
                <span className="bg-gradient-to-r from-gray-900 to-rose-800 bg-clip-text text-transparent">Homborsund Community Center</span>
              ) : (
                "Homborsund Community Center"
              )}
            </h2>
            <p className="max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400">
              The summit will be held at the Vågsholt skole, a historic building located in the heart
              of Krømpe.
            </p>
          </div>
          <div className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-2 lg:gap-12">
            <iframe
              className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center w-full"
              frameBorder="0"
              style={{ border: 0, maxWidth: '100%' }}
              src={`https://www.google.com/maps/embed/v1/place?key=${process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}&q=Krømpe+16,Grimstad,Norway&zoom=10`}
              allowFullScreen
              title="Google Maps"
            />
            <div className="space-y-4">
              <div className="grid gap-1">
                <h3 className="text-xl font-bold">Address</h3>
                <p className="text-gray-500 dark:text-gray-400">Krømpe 16, Grimstad, Eide, Norway</p>
              </div>
              <div className="grid gap-1">
                <h3 className="text-xl font-bold">Parking</h3>
                <p className="text-gray-500 dark:text-gray-400">Free parking is available on-site.</p>
              </div>
              <div className="grid gap-1">
                <h3 className="text-xl font-bold">Accessibility</h3>
                <p className="text-gray-500 dark:text-gray-400">The venue is wheelchair accessible.</p>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section id="experience" className="w-full py-12 md:py-24 lg:py-32 bg-gray-50 dark:bg-gray-900 scroll-mt-16">
        <div className="container px-4 md:px-6">
          <div className="flex flex-col items-center text-center space-y-4">
            <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">The Experience</div>
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Back to Our Roots</h2>
            <p className="max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400">
              Embracing the authentic Norwegian experience, our summit offers a refreshing departure from the usual tech-laden conferences.
            </p>
            
            <div className="mx-auto grid max-w-5xl items-center gap-8 py-12 lg:grid-cols-2 lg:gap-12">
              <div className="space-y-4">
                <h3 className="text-2xl font-bold">Authentic Facilities</h3>
                <div className="space-y-2">
                  <p className="text-gray-500 dark:text-gray-400">
                    <span className="font-semibold">Traditional &quot;Utedo&quot;:</span> Experience our charming Norwegian outdoor toilet facility, a perfect opportunity to connect with nature while disconnecting from technology.
                  </p>
                  <p className="text-gray-500 dark:text-gray-400">
                    <span className="font-semibold">No Electricity or Running Water:</span> Detach completely from digital dependencies. We&apos;ll use candles, lanterns, and stars to light our discussions—just like the pioneers of science and philosophy did for centuries.
                  </p>
                  <p className="text-gray-500 dark:text-gray-400">
                    <span className="font-semibold">What to Bring:</span> A flashlight, comfortable warm clothes, your favorite drinks, and food to share. We&apos;ll provide basic necessities, warm fires, and plenty of inspiration.
                  </p>
                </div>
              </div>
              
              <div className="space-y-4">
                <h3 className="text-2xl font-bold">Why Unplug?</h3>
                <div className="space-y-2">
                  <p className="text-gray-500 dark:text-gray-400">
                    As AI models like GPT-4.5 Orion and Claude 3.7 become increasingly natural in conversation and ever more capable, our summit offers a counterpoint: genuine human connection in its purest form.
                  </p>
                  <p className="text-gray-500 dark:text-gray-400">
                    In a world where AI can now generate working code, create interactive visualizations, and solve complex math problems with ease, we believe that human creativity still flourishes best in nature, away from screens.
                  </p>
                  <p className="text-gray-500 dark:text-gray-400">
                    <span className="italic">&quot;Some of my best ideas came when I was furthest from technology.&quot;</span> — Previous attendee
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section id="register" className="w-full py-12 md:py-24 lg:py-32 border-t scroll-mt-16">
        <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
          <div className="space-y-3">
            <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">
              {activeYear === DEFAULT_YEAR ? (
                <span className="bg-gradient-to-r from-rose-800 to-indigo-700 bg-clip-text text-transparent">Join us at the Homborsund AI Summit {activeYear}</span>
              ) : (
                `Join us at the Homborsund AI Summit ${activeYear}`
              )}
            </h2>
            <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              {activeSummit.status === "Upcoming" 
                ? "Register now to secure your spot and be a part of this exciting event where cutting-edge AI concepts meet authentic human connection."
                : "This event has concluded. Check out our upcoming summit!"}
            </p>
          </div>
          <div className="mx-auto w-full max-w-sm space-y-2">
            {activeSummit.status === "Upcoming" ? (
              <>
                <Link
                  className={`inline-flex h-10 items-center justify-center rounded-md px-8 text-sm font-medium text-gray-50 shadow transition-colors focus-visible:outline-none focus-visible:ring-1 disabled:pointer-events-none disabled:opacity-50 ${
                    activeYear === DEFAULT_YEAR
                      ? "bg-gradient-to-r from-rose-800 to-purple-700 hover:from-rose-700 hover:to-purple-600 focus-visible:ring-rose-500"
                      : "bg-gray-900 hover:bg-gray-900/90 focus-visible:ring-gray-950 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
                  }`}
                  href="https://chat.whatsapp.com/FWv18Iz2r59CuQb98LBuUQ"
                >
                  Register Now
                </Link>
                <p className="text-xs text-gray-500 dark:text-gray-400">Early bird tickets available until March 1st, 2025. Limited to 30 participants for an intimate experience. Join our WhatsApp community.</p>
              </>
            ) : (
              <Link
                href={`/summit/${DEFAULT_YEAR}`}
                className="inline-flex h-10 items-center justify-center rounded-md bg-gray-900 px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
              >
                View Upcoming Summit
              </Link>
            )}
          </div>
        </div>
      </section>
      
      {/* Past Summits Section - Only shown when viewing past summits */}
      {activeSummit.status === "Completed" && (
        <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center text-center space-y-4">
              <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">Archive</div>
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Past Summits</h2>
              <p className="max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400">
                Take a look at our previous AI summits and the amazing discussions we had.
              </p>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mt-8">
                {/* Photo gallery from past summit */}
                <div className="space-y-4">
                  <h3 className="text-2xl font-semibold">Photo Highlights</h3>
                  <div className="grid grid-cols-2 gap-2">
                    {[1, 2, 3, 4].map((num) => (
                      <div key={num} className="aspect-square bg-gray-200 rounded-md flex items-center justify-center">
                        <span className="text-gray-500">Photo {num}</span>
                      </div>
                    ))}
                  </div>
                </div>
                
                {/* Testimonials from past summit */}
                <div className="space-y-4">
                  <h3 className="text-2xl font-semibold">Attendee Feedback</h3>
                  <div className="space-y-4">
                    <blockquote className="border-l-4 border-rose-800 pl-4 italic">
                      &quot;The discussions were eye-opening. Can&apos;t wait for next year&apos;s summit!&quot;
                      <footer className="text-sm mt-2">— Previous Attendee</footer>
                    </blockquote>
                    <blockquote className="border-l-4 border-rose-800 pl-4 italic">
                      &quot;A perfect blend of technical insights and practical applications.&quot;
                      <footer className="text-sm mt-2">— AI Enthusiast</footer>
                    </blockquote>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      )}
    </main>
  )
}
