"use client";

/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/2ueqsatE71o
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Taviraj } from 'next/font/google'

taviraj({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import Image from "next/image"
import { useEffect } from "react"

type SummitData = {
  title: string;
  date: string;
  theme: string;
  description: string[];
  schedule: { time: string; event: string }[];
  status: 'Upcoming' | 'Completed';
}

type SummitsData = {
  [key: string]: SummitData;
}

const summits: SummitsData = {
  "2024": {
    title: "Homborsund AI Conference",
    date: "August 17th 2024",
    theme: "Back to Basics",
    description: [
      "Join us for a deep dive into the fundamentals of AI, where we'll explore the core concepts and techniques that power the latest advancements.",
      "No tech allowed, just you and your curiosity."
    ],
    schedule: [
      { time: "16:00 - 18:00", event: "Drinks and food, networking" },
      { time: "18:00 - 19:30", event: "Various introductions" },
      { time: "19:30 - 21:00", event: "AI: Are we there yet?" },
      { time: "21:00 - 22:00", event: "And what next?" },
      { time: "22:00 - Late", event: "Let's talk about it" }
    ],
    status: "Completed"
  },
  "2025": {
    title: "Homborsund AI Summit",
    date: "3. Mai 2025",
    theme: "Beyond GenAI: The Hardware Wars & ML Revolution",
    description: [
      "The second annual gathering for AI enthusiasts and professionals to discuss real-world applications and the future of artificial intelligence.",
      "Experience the latest breakthroughs in AI just weeks after the release of GPT-4.5 Orion, Claude 3.7 Sonnet, and Grok 3 — the first 'Generation 3' models with 10x the computing power of their predecessors.",
      "But it's not all about GenAI! This year we're diving deep into the silicon battles and ML frameworks that power our AI overlords.",
      "No tech allowed, just you and your curiosity — we'll provide the inspiration in nature's own environment, far from the hum of NVIDIA's H200 server farms."
    ],
    schedule: [
      { time: "16:00 - 18:00", event: "Welcome reception and networking (please bring food and drinks to share - bring something that even a trained chef ML model would approve of!)" },
      { time: "18:00 - 19:00", event: "Opening keynote: 'The Great GPU Hunger Games' - How NVIDIA went from gaming company to AI overlord, and why Jensen Huang's leather jacket contains more computing power than the entire Internet circa 2005" },
      { time: "19:00 - 20:00", event: "Panel: 'DeepSeek vs NVIDIA: David's Slingshot Moment' - How DeepSeek's R1 model is challenging NVIDIA's dominance by bypassing traditional GPU constraints" },
      { time: "20:00 - 21:00", event: "Workshop: 'Traditional ML's Revenge: When Simple Models Beat Giant Transformers' - Interactive demonstrations of when good old decision trees and random forests outperform their ChatGPT cousins" },
      { time: "21:00 - 22:00", event: "Debate: 'ML vs GenAI: The Battle for AI's Soul' - Has the GenAI hype overshadowed the steady progress in traditional ML? Two teams, one utedo toilet break, unlimited philosophical ammunition" },
      { time: "22:00 - Late", event: "Campfire discussions under the stars - 'Ghost Stories About Runaway Training Jobs and Other AI Horrors' - Bring blankets, warm drinks, and your most expensive failed experiment stories" }
    ],
    status: "Upcoming"
  }
}

type ConferanceProps = {
  year?: string;
}

export function Conferance({ year = "2025" }: ConferanceProps) {
  const activeYear = Object.keys(summits).includes(year) ? year : "2025";
  const activeSummit = summits[activeYear];

  // Add smooth scrolling for anchor links
  useEffect(() => {
    const handleAnchorClick = (e: MouseEvent) => {
      const target = e.target as HTMLElement;
      if (target.tagName === 'A' && target.getAttribute('href')?.startsWith('#')) {
        e.preventDefault();
        const id = target.getAttribute('href')?.substring(1);
        const element = document.getElementById(id || '');
        if (element) {
          window.scrollTo({
            top: element.offsetTop - 80, // Offset to account for sticky header/padding
            behavior: 'smooth'
          });
        }
      }
    };

    document.addEventListener('click', handleAnchorClick);
    return () => document.removeEventListener('click', handleAnchorClick);
  }, []);

  return (
    <main className="flex flex-col">
      <section className="w-full py-6 md:py-12 bg-gray-100 dark:bg-gray-800">
        <div className="container px-4 md:px-6">
          <div className="flex flex-row justify-center gap-4 mb-8">
            {Object.keys(summits).map((summitYear) => (
              <Link
                key={summitYear}
                href={`/?year=${summitYear}`}
                className={`px-6 py-2 rounded-md ${
                  activeYear === summitYear 
                    ? "bg-rose-800 text-white font-bold" 
                    : "bg-gray-200 text-gray-700 hover:bg-gray-300 dark:bg-gray-700 dark:text-gray-200"
                }`}
              >
                Summit {summitYear}
                {summits[summitYear].status === "Upcoming" && (
                  <span className="ml-2 text-xs bg-green-500 text-white px-2 py-0.5 rounded-full">
                    Next
                  </span>
                )}
              </Link>
            ))}
          </div>

          <div className="flex flex-col items-center text-center space-y-4">
            <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl">{activeSummit.title}</h1>
            <p className="text-3xl text-rose-800 tracking-tighter sm:text-4xl md:text-5xl">{activeSummit.date}</p>
            <p className="max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400">{activeSummit.theme}</p>
            {activeSummit.description.map((paragraph, index) => (
              <p key={index} className="max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400">
                {paragraph}
              </p>
            ))}
            
            {/* Navigation links for 2025 */}
            {activeYear === "2025" && (
              <div className="w-full max-w-4xl mt-8">
                <h3 className="text-lg font-medium mb-4">Jump to a section:</h3>
                <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-3">
                  <a href="#schedule" className="bg-gradient-to-r from-rose-600 to-rose-800 text-white px-4 py-3 rounded-lg shadow-md hover:shadow-lg transition-all text-sm md:text-base text-center font-medium flex items-center justify-center">
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
                    </svg>
                    Schedule
                  </a>
                  <a href="#topics" className="bg-gradient-to-r from-rose-600 to-purple-700 text-white px-4 py-3 rounded-lg shadow-md hover:shadow-lg transition-all text-sm md:text-base text-center font-medium flex items-center justify-center">
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
                    </svg>
                    Hot Topics
                  </a>
                  <a href="#norwegian" className="bg-gradient-to-r from-green-600 to-green-800 text-white px-4 py-3 rounded-lg shadow-md hover:shadow-lg transition-all text-sm md:text-base text-center font-medium flex items-center justify-center">
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3.055 11H5a2 2 0 012 2v1a2 2 0 002 2 2 2 0 012 2v2.945M8 3.935V5.5A2.5 2.5 0 0010.5 8h.5a2 2 0 012 2 2 2 0 104 0 2 2 0 012-2h1.064M15 20.488V18a2 2 0 012-2h3.064M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                    Norwegian ML
                  </a>
                  <a href="#attend" className="bg-gradient-to-r from-gray-700 to-gray-900 text-white px-4 py-3 rounded-lg shadow-md hover:shadow-lg transition-all text-sm md:text-base text-center font-medium flex items-center justify-center">
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z" />
                    </svg>
                    How to Attend
                  </a>
                  <a href="#speakers" className="bg-gradient-to-r from-blue-600 to-blue-800 text-white px-4 py-3 rounded-lg shadow-md hover:shadow-lg transition-all text-sm md:text-base text-center font-medium flex items-center justify-center">
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" />
                    </svg>
                    Speakers
                  </a>
                  <a href="#venue" className="bg-gradient-to-r from-amber-600 to-amber-800 text-white px-4 py-3 rounded-lg shadow-md hover:shadow-lg transition-all text-sm md:text-base text-center font-medium flex items-center justify-center">
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" />
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" />
                    </svg>
                    Venue
                  </a>
                  <a href="#experience" className="bg-gradient-to-r from-indigo-600 to-indigo-800 text-white px-4 py-3 rounded-lg shadow-md hover:shadow-lg transition-all text-sm md:text-base text-center font-medium flex items-center justify-center">
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 7v10a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-6l-2-2H5a2 2 0 00-2 2z" />
                    </svg>
                    Experience
                  </a>
                  <a href="#register" className="bg-gradient-to-r from-rose-500 to-rose-700 text-white px-4 py-3 rounded-lg shadow-md hover:shadow-lg transition-all text-sm md:text-base text-center font-medium flex items-center justify-center col-span-2 md:col-span-1">
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M11 16l-4-4m0 0l4-4m-4 4h14m-5 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h7a3 3 0 013 3v1" />
                    </svg>
                    Register Now
                  </a>
                </div>
              </div>
            )}
          </div>
        </div>
      </section>
      <section id="schedule" className="w-full py-12 md:py-24 lg:py-32 scroll-mt-16">
        <div className="container px-4 md:px-6">
          <div className="flex flex-col items-center text-center space-y-4">
            <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">Schedule</div>
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Summit Schedule</h2>
            <p className="max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400">
              Explore the lineup of thought-provoking talks and interactive sessions.
            </p>
          </div>
          <div className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-1 lg:gap-12">
            <div className="space-y-4">
              <div className="grid gap-1">
                <h3 className="text-xl font-bold">Day 1</h3>
                {activeSummit.schedule.map((item, index) => (
                  <p key={index} className="text-gray-500 dark:text-gray-400">
                    {item.time}: {item.event}
                  </p>
                ))}
              </div>
            </div>
          </div>
        </div>
      </section>
      {/* Add Hot Topics section between Schedule and Speakers sections */}
      {activeYear === "2025" && (
        <section id="topics" className="w-full py-12 md:py-24 lg:py-32 bg-rose-50 dark:bg-gray-900 scroll-mt-16">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center text-center space-y-4">
              <div className="inline-block rounded-lg bg-rose-100 px-3 py-1 text-sm dark:bg-gray-800">Hot Topics</div>
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">2025's Cutting-Edge AI Trends</h2>
              <p className="max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400">
                Our summit will explore the most revolutionary AI developments just emerging in 2025.
              </p>
            </div>
            
            <div className="mx-auto grid max-w-5xl items-center gap-8 py-12 md:grid-cols-2 lg:grid-cols-3">
              <div className="flex flex-col p-6 space-y-4 bg-white rounded-xl shadow-sm dark:bg-gray-800">
                <div className="text-rose-800 text-4xl font-bold">01</div>
                <h3 className="text-xl font-bold">GPT-4.5 Orion's Emotional Intelligence</h3>
                <p className="text-gray-500 dark:text-gray-400">
                  Explore how OpenAI's newest model achieves unprecedented emotional understanding and world knowledge, creating more nuanced and contextually aware responses.
                </p>
              </div>
              
              <div className="flex flex-col p-6 space-y-4 bg-white rounded-xl shadow-sm dark:bg-gray-800">
                <div className="text-rose-800 text-4xl font-bold">02</div>
                <h3 className="text-xl font-bold">Claude 3.7's Reasoning Capabilities</h3>
                <p className="text-gray-500 dark:text-gray-400">
                  Anthropic's Claude 3.7 Sonnet introduces revolutionary reasoning abilities that allow it to solve complex problems step-by-step with minimal errors.
                </p>
              </div>
              
              <div className="flex flex-col p-6 space-y-4 bg-white rounded-xl shadow-sm dark:bg-gray-800">
                <div className="text-rose-800 text-4xl font-bold">03</div>
                <h3 className="text-xl font-bold">NVIDIA's H200 vs DeepSeek Revolution</h3>
                <p className="text-gray-500 dark:text-gray-400">
                  The great silicon showdown: NVIDIA's $40,000 H200 GPUs power most AI, but DeepSeek's R1 model challenges this dominance with a radically different approach that bypasses traditional APIs.
                </p>
              </div>
              
              <div className="flex flex-col p-6 space-y-4 bg-white rounded-xl shadow-sm dark:bg-gray-800">
                <div className="text-rose-800 text-4xl font-bold">04</div>
                <h3 className="text-xl font-bold">ML's Renaissance: XGBoost Strikes Back</h3>
                <p className="text-gray-500 dark:text-gray-400">
                  While GenAI hogs the spotlight, traditional machine learning frameworks have evolved—sometimes outperforming transformer models with 1/1000th the parameters. Come witness XGBoost's revenge tour.
                </p>
              </div>
              
              <div className="flex flex-col p-6 space-y-4 bg-white rounded-xl shadow-sm dark:bg-gray-800">
                <div className="text-rose-800 text-4xl font-bold">05</div>
                <h3 className="text-xl font-bold">MoE Architecture: When One Expert Isn't Enough</h3>
                <p className="text-gray-500 dark:text-gray-400">
                  DeepSeek's 671B parameter Mixture-of-Experts model demonstrates how specialized neural pathways—not just raw parameter count—drive breakthrough performance at a fraction of the training cost.
                </p>
              </div>
              
              <div className="flex flex-col p-6 space-y-4 bg-white rounded-xl shadow-sm dark:bg-gray-800">
                <div className="text-rose-800 text-4xl font-bold">06</div>
                <h3 className="text-xl font-bold">The GPU-Less Future?</h3>
                <p className="text-gray-500 dark:text-gray-400">
                  Is Jensen Huang's leather jacket collection at risk? Explore how novel training approaches, specialized AI chips, and open-source innovations might finally break NVIDIA's AI monopoly.
                </p>
              </div>
            </div>
          </div>
        </section>
      )}
      {/* Add new Norwegian Experience section before the Venue section */}
      {activeYear === "2025" && (
        <section id="norwegian" className="w-full py-12 md:py-24 lg:py-32 bg-green-50 dark:bg-gray-900 scroll-mt-16">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center text-center space-y-4">
              <div className="inline-block rounded-lg bg-green-100 px-3 py-1 text-sm dark:bg-gray-800">Norwegian ML Experience</div>
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Machine Learning, Norwegian Style</h2>
              <p className="max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400">
                What Norway lacks in silicon, we make up for in scenic beauty and philosophical clarity.
              </p>
            </div>
            
            <div className="mx-auto grid max-w-5xl items-center gap-8 py-12 lg:grid-cols-1">
              <div className="flex flex-col p-6 space-y-6 bg-white rounded-xl shadow-sm dark:bg-gray-800">
                <h3 className="text-2xl font-bold">The Norwegian ML Philosophy</h3>
                <p className="text-gray-500 dark:text-gray-400">
                  While Silicon Valley argues about which $100 million model is best, Norwegians have been quietly applying ML in practical ways that actually help people. Learn how:
                </p>
                <ul className="space-y-2 text-gray-500 dark:text-gray-400 text-left list-disc pl-5">
                  <li><span className="font-bold">Neural nets for fishing forecasts:</span> Local ML models predict optimal fishing conditions with 85% accuracy using 1000x less compute than a single ChatGPT query</li>
                  <li><span className="font-bold">Random forests for actual forests:</span> Predicting bark beetle outbreaks using lightweight ML that runs on solar power</li>
                  <li><span className="font-bold">Gradient boosting vs. avalanches:</span> How a 5MB model saves lives every winter</li>
                  <li><span className="font-bold">When your utedo needs AI:</span> (Trick topic - utedos definitely don't need AI, and that's the point!)</li>
                </ul>
                <p className="text-gray-500 dark:text-gray-400 italic">
                  &quot;Sometimes the most advanced technology is knowing when to use no technology at all.&quot; — Norwegian proverb we just made up but sounds legit
                </p>
              </div>
            </div>
          </div>
        </section>
      )}
      {/* Add How to Attend section for 2025 summit */}
      {activeYear === "2025" && (
        <section id="attend" className="w-full py-12 md:py-24 lg:py-32 bg-gray-900 text-white scroll-mt-16">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center text-center space-y-4">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl text-rose-500">How to Attend</h2>
              <p className="max-w-[700px] text-gray-300 md:text-xl font-medium">
                The Homborsund AI Summit is an invitation... that you extend to yourself.
              </p>
            </div>
            
            <div className="mx-auto grid max-w-5xl items-center gap-8 py-12 md:grid-cols-1 lg:grid-cols-3">
              <div className="flex flex-col h-full">
                <div className="relative">
                  <div className="absolute top-0 left-0 w-full h-1 bg-rose-500"></div>
                </div>
                <div className="flex flex-col items-center space-y-3 p-6">
                  <div className="bg-rose-100 rounded-full p-4 mb-2">
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-8 w-8 text-rose-800" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M11 5.882V19.24a1.76 1.76 0 01-3.417.592l-2.147-6.15M18 13a3 3 0 100-6M5.436 13.683A4.001 4.001 0 017 6h1.832c4.1 0 7.625-1.234 9.168-3v14c-1.543-1.766-5.067-3-9.168-3H7a3.988 3.988 0 01-1.564-.317z" />
                    </svg>
                  </div>
                  <h3 className="text-xl font-bold text-white">Want to Attend?</h3>
                  <p className="text-gray-300 text-center">
                    That's the first and most important step. If you're reading this and thinking "I'd like to be there" - congratulations, you've completed the most crucial part of the registration process.
                  </p>
                </div>
              </div>
              
              <div className="flex flex-col h-full">
                <div className="relative">
                  <div className="absolute top-0 left-0 w-full h-1 bg-rose-500"></div>
                </div>
                <div className="flex flex-col items-center space-y-3 p-6">
                  <div className="bg-rose-100 rounded-full p-4 mb-2">
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-8 w-8 text-rose-800" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" />
                    </svg>
                  </div>
                  <h3 className="text-xl font-bold text-white">Know Something</h3>
                  <p className="text-gray-300 text-center">
                    Bring your knowledge—whether it's vast expertise in transformer architectures or just a persistent curiosity about why ChatGPT hallucinates your birthday. What matters is what YOU know, and what YOU want to learn.
                  </p>
                </div>
              </div>
              
              <div className="flex flex-col h-full">
                <div className="relative">
                  <div className="absolute top-0 left-0 w-full h-1 bg-rose-500"></div>
                </div>
                <div className="flex flex-col items-center space-y-3 p-6">
                  <div className="bg-rose-100 rounded-full p-4 mb-2">
                    <svg xmlns="http://www.w3.org/2000/svg" className="h-8 w-8 text-rose-800" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z" />
                    </svg>
                  </div>
                  <h3 className="text-xl font-bold text-white">Tell Someone</h3>
                  <p className="text-gray-300 text-center">
                    Invite yourself by clicking the registration link, then tell a fellow AI enthusiast about the summit. The best learning happens in small groups of passionate people—each person you invite enriches the experience for everyone.
                  </p>
                </div>
              </div>

              <div className="md:col-span-1 lg:col-span-3 mt-6">
                <div className="p-6 rounded-xl border-l-4 border-rose-500">
                  <h3 className="text-2xl font-bold mb-4 text-white">The Self-Invitation Philosophy</h3>
                  <p className="text-gray-300 mb-4">
                    Unlike mainstream conferences with prohibitive price tags and elaborate registration processes, we believe in simplicity. If you feel called to join our gathering of minds, we trust that you'll:
                  </p>
                  <ul className="space-y-3 text-gray-300">
                    <li className="flex items-start">
                      <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-rose-500 mr-2 flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                      </svg>
                      <span><strong>Bring the right spirit</strong> — A blend of curiosity, openness, and willingness to disconnect from technology to connect with ideas and people</span>
                    </li>
                    <li className="flex items-start">
                      <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-rose-500 mr-2 flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                      </svg>
                      <span><strong>Contribute to the potluck</strong> — Both literally (bring food/drinks) and figuratively (bring ideas, questions, and enthusiasm)</span>
                    </li>
                    <li className="flex items-start">
                      <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6 text-rose-500 mr-2 flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z" />
                      </svg>
                      <span><strong>Extend the circle</strong> — Invite someone who would add value to our discussions (but remember space is limited to 30 participants)</span>
                    </li>
                  </ul>
                  <p className="mt-4 text-rose-400 italic font-medium">
                    &quot;The best gatherings are those where each person feels personally responsible for its success.&quot;
                  </p>
                </div>
              </div>
            </div>
            
            <div className="flex flex-col items-center mt-8">
              <Link 
                href="https://discord.gg/5rQ9XGYdqJ" 
                className="inline-flex h-12 items-center justify-center rounded-md bg-rose-600 px-8 text-base font-medium text-white shadow transition-colors hover:bg-rose-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-rose-500 disabled:pointer-events-none disabled:opacity-50 transform transition-transform duration-200 hover:scale-105"
              >
                I'm Inviting Myself
              </Link>
              <p className="text-sm text-gray-400 mt-3">
                Join our Discord first, then introduce yourself in the #summit-2025 channel
              </p>
            </div>
          </div>
        </section>
      )}
      <section id="speakers" className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800 scroll-mt-16">
        <div className="container px-4 md:px-6">
          <div className="flex flex-col items-center text-center space-y-4">
            <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">Speakers</div>
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Meet the Speakers</h2>
            <p className="max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400">
              Learn from industry experts and thought leaders in the field of AI.
            </p>
          </div>
          <div className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-3 lg:gap-12">
            <div className="flex flex-col items-center space-y-4">
              <Image
                alt="Speaker"
                className="rounded-full"
                height="150"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "150/150",
                  objectFit: "cover",
                }}
                width="150"
              />
              <div className="space-y-1 text-center">
                <h3 className="text-xl font-bold">Eivind</h3>
                <p className="text-gray-500 dark:text-gray-400">Random TOGAF nerd</p>
              </div>
            </div>
            <div className="flex flex-col items-center space-y-4">
              <Image
                alt="Speaker"
                className="rounded-full"
                height="150"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "150/150",
                  objectFit: "cover",
                }}
                width="150"
              />
              <div className="space-y-1 text-center">
                <h3 className="text-xl font-bold">Øyvind</h3>
                <p className="text-gray-500 dark:text-gray-400">Random dev nerd</p>
              </div>
            </div>
            <div className="flex flex-col items-center space-y-4">
              <Image
                alt="Speaker"
                className="rounded-full"
                height="150"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "150/150",
                  objectFit: "cover",
                }}
                width="150"
              />
              <div className="space-y-1 text-center">
                <h3 className="text-xl font-bold">Rebekka (please come!)</h3>
                <p className="text-gray-500 dark:text-gray-400">Random AI nerd</p>
              </div>
            </div>
          </div>
          <div className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-3 lg:gap-12">
            <div className="flex flex-col items-center space-y-4">
              <Image
                alt="Speaker"
                className="rounded-full"
                height="150"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "150/150",
                  objectFit: "cover",
                }}
                width="150"
              />
              <div className="space-y-1 text-center">
                <h3 className="text-xl font-bold">Lars</h3>
                <p className="text-gray-500 dark:text-gray-400">Random ERP nerd</p>
              </div>
            </div>
            <div className="flex flex-col items-center space-y-4">
              <Image
                alt="Speaker"
                className="rounded-full"
                height="150"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "150/150",
                  objectFit: "cover",
                }}
                width="150"
              />
              <div className="space-y-1 text-center">
                <h3 className="text-xl font-bold">Andreas</h3>
                <p className="text-gray-500 dark:text-gray-400">Random robotics nerd</p>
              </div>
            </div>
            <div className="flex flex-col items-center space-y-4">
              <Image
                alt="Speaker"
                className="rounded-full"
                height="150"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "150/150",
                  objectFit: "cover",
                }}
                width="150"
              />
              <div className="space-y-1 text-center">
                <h3 className="text-xl font-bold">And you!</h3>
                <p className="text-gray-500 dark:text-gray-400">...</p>
              </div>
            </div>
            <div className="flex flex-col items-center space-y-4">
              <Image
                alt="Speaker"
                className="rounded-full"
                height={150}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "150/150",
                  objectFit: "cover",
                }}
                width={150}
              />
              <div className="space-y-1 text-center">
                <h3 className="text-xl font-bold">Ofc, you!</h3>
                <p className="text-gray-500 dark:text-gray-400">....</p>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section id="venue" className="w-full py-12 md:py-24 lg:py-32 scroll-mt-16">
        <div className="container px-4 md:px-6">
          <div className="flex flex-col items-center text-center space-y-4">
            <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">Venue</div>
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
              {activeYear === "2025" ? (
                <span className="bg-gradient-to-r from-gray-900 to-rose-800 bg-clip-text text-transparent">Homborsund Community Center</span>
              ) : (
                "Homborsund Community Center"
              )}
            </h2>
            <p className="max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400">
              The summit will be held at the Vågsholt skole, a historic building located in the heart
              of Krømpe.
            </p>
          </div>
          <div className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-2 lg:gap-12">
            <iframe
              className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full"
              width="550"
              height="310"
              frameBorder="0"
              style={{ border: 0 }}
              src={`https://www.google.com/maps/embed/v1/place?key=${process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}&q=Krømpe+16,Grimstad,Norway&zoom=10`}
              allowFullScreen
              title="Google Maps"
            />
            <div className="space-y-4">
              <div className="grid gap-1">
                <h3 className="text-xl font-bold">Address</h3>
                <p className="text-gray-500 dark:text-gray-400">Krømpe 16, Grimstad, Eide, Norway</p>
              </div>
              <div className="grid gap-1">
                <h3 className="text-xl font-bold">Parking</h3>
                <p className="text-gray-500 dark:text-gray-400">Free parking is available on-site.</p>
              </div>
              <div className="grid gap-1">
                <h3 className="text-xl font-bold">Accessibility</h3>
                <p className="text-gray-500 dark:text-gray-400">The venue is wheelchair accessible.</p>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section id="experience" className="w-full py-12 md:py-24 lg:py-32 bg-gray-50 dark:bg-gray-900 scroll-mt-16">
        <div className="container px-4 md:px-6">
          <div className="flex flex-col items-center text-center space-y-4">
            <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">The Experience</div>
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Back to Our Roots</h2>
            <p className="max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400">
              Embracing the authentic Norwegian experience, our summit offers a refreshing departure from the usual tech-laden conferences.
            </p>
            
            <div className="mx-auto grid max-w-5xl items-center gap-8 py-12 lg:grid-cols-2 lg:gap-12">
              <div className="space-y-4">
                <h3 className="text-2xl font-bold">Authentic Facilities</h3>
                <div className="space-y-2">
                  <p className="text-gray-500 dark:text-gray-400">
                    <span className="font-semibold">Traditional "Utedo":</span> Experience our charming Norwegian outdoor toilet facility, a perfect opportunity to connect with nature while disconnecting from technology.
                  </p>
                  <p className="text-gray-500 dark:text-gray-400">
                    <span className="font-semibold">No Electricity or Running Water:</span> Detach completely from digital dependencies. We'll use candles, lanterns, and stars to light our discussions—just like the pioneers of science and philosophy did for centuries.
                  </p>
                  <p className="text-gray-500 dark:text-gray-400">
                    <span className="font-semibold">What to Bring:</span> A flashlight, comfortable warm clothes, your favorite drinks, and food to share. We'll provide basic necessities, warm fires, and plenty of inspiration.
                  </p>
                </div>
              </div>
              
              <div className="space-y-4">
                <h3 className="text-2xl font-bold">Why Unplug?</h3>
                <div className="space-y-2">
                  <p className="text-gray-500 dark:text-gray-400">
                    As AI models like GPT-4.5 Orion and Claude 3.7 become increasingly natural in conversation and ever more capable, our summit offers a counterpoint: genuine human connection in its purest form.
                  </p>
                  <p className="text-gray-500 dark:text-gray-400">
                    In a world where AI can now generate working code, create interactive visualizations, and solve complex math problems with ease, we believe that human creativity still flourishes best in nature, away from screens.
                  </p>
                  <p className="text-gray-500 dark:text-gray-400">
                    <span className="italic">&quot;Some of my best ideas came when I was furthest from technology.&quot;</span> — Previous attendee
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section id="register" className="w-full py-12 md:py-24 lg:py-32 border-t scroll-mt-16">
        <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
          <div className="space-y-3">
            <h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">
              {activeYear === "2025" ? (
                <span className="bg-gradient-to-r from-rose-800 to-indigo-700 bg-clip-text text-transparent">Join us at the Homborsund AI Summit {activeYear}</span>
              ) : (
                `Join us at the Homborsund AI Summit ${activeYear}`
              )}
            </h2>
            <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              {activeSummit.status === "Upcoming" 
                ? "Register now to secure your spot and be a part of this exciting event where cutting-edge AI concepts meet authentic human connection."
                : "This event has concluded. Check out our upcoming summit!"}
            </p>
          </div>
          <div className="mx-auto w-full max-w-sm space-y-2">
            {activeSummit.status === "Upcoming" ? (
              <>
                <Link
                  className={`inline-flex h-10 items-center justify-center rounded-md px-8 text-sm font-medium text-gray-50 shadow transition-colors focus-visible:outline-none focus-visible:ring-1 disabled:pointer-events-none disabled:opacity-50 ${
                    activeYear === "2025" 
                      ? "bg-gradient-to-r from-rose-800 to-purple-700 hover:from-rose-700 hover:to-purple-600 focus-visible:ring-rose-500"
                      : "bg-gray-900 hover:bg-gray-900/90 focus-visible:ring-gray-950 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
                  }`}
                  href="https://discord.gg/5rQ9XGYdqJ"
                >
                  Register Now
                </Link>
                <p className="text-xs text-gray-500 dark:text-gray-400">Early bird tickets available until March 1st, 2025. Limited to 30 participants for an intimate experience.</p>
              </>
            ) : (
              <Link
                href="/?year=2025"
                className="inline-flex h-10 items-center justify-center rounded-md bg-gray-900 px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
              >
                View Upcoming Summit
              </Link>
            )}
          </div>
        </div>
      </section>
      
      {/* Past Summits Section - Only shown when viewing past summits */}
      {activeSummit.status === "Completed" && (
        <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
          <div className="container px-4 md:px-6">
            <div className="flex flex-col items-center text-center space-y-4">
              <div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">Archive</div>
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Past Summits</h2>
              <p className="max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400">
                Take a look at our previous AI summits and the amazing discussions we had.
              </p>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mt-8">
                {/* Photo gallery from past summit */}
                <div className="space-y-4">
                  <h3 className="text-2xl font-semibold">Photo Highlights</h3>
                  <div className="grid grid-cols-2 gap-2">
                    {[1, 2, 3, 4].map((num) => (
                      <div key={num} className="aspect-square bg-gray-200 rounded-md flex items-center justify-center">
                        <span className="text-gray-500">Photo {num}</span>
                      </div>
                    ))}
                  </div>
                </div>
                
                {/* Testimonials from past summit */}
                <div className="space-y-4">
                  <h3 className="text-2xl font-semibold">Attendee Feedback</h3>
                  <div className="space-y-4">
                    <blockquote className="border-l-4 border-rose-800 pl-4 italic">
                      &quot;The discussions were eye-opening. Can't wait for next year's summit!&quot;
                      <footer className="text-sm mt-2">— Previous Attendee</footer>
                    </blockquote>
                    <blockquote className="border-l-4 border-rose-800 pl-4 italic">
                      &quot;A perfect blend of technical insights and practical applications.&quot;
                      <footer className="text-sm mt-2">— AI Enthusiast</footer>
                    </blockquote>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      )}
    </main>
  )
}
